name: github pages

on:
  push:
    branches:
      - move-to-hugo-doks
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install npm packages
        run: |
          npm install # reads info from package.js

      - name: Build
        run: hugo --minify --config _default/config.toml,_default/menus.toml,_default/params.toml,production/config.toml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/move-to-hugo-doks'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
